interactions:
- request:
    body: null
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - promptflow-azure-sdk/1.11.0.dev0 azure-ai-ml/1.15.0 azsdk-python-mgmt-machinelearningservices/0.1.0
        Python/3.11.5 (Windows-10-10.0.22621-SP0)
    method: GET
    uri: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/00000/providers/Microsoft.MachineLearningServices/workspaces/00000
  response:
    body:
      string: '{"id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/00000/providers/Microsoft.MachineLearningServices/workspaces/00000",
        "name": "00000", "type": "Microsoft.MachineLearningServices/workspaces", "location":
        "eastus", "tags": {}, "etag": null, "kind": "Default", "sku": {"name": "Basic",
        "tier": "Basic"}, "properties": {"discoveryUrl": "https://eastus.api.azureml.ms/discovery"}}'
    headers:
      cache-control:
      - no-cache
      content-length:
      - '3750'
      content-type:
      - application/json; charset=utf-8
      expires:
      - '-1'
      pragma:
      - no-cache
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      vary:
      - Accept-Encoding
      x-cache:
      - CONFIG_NOCACHE
      x-content-type-options:
      - nosniff
      x-request-time:
      - '0.034'
    status:
      code: 200
      message: OK
- request:
    body: null
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - promptflow-azure-sdk/1.11.0.dev0 azure-ai-ml/1.15.0 azsdk-python-mgmt-machinelearningservices/0.1.0
        Python/3.11.5 (Windows-10-10.0.22621-SP0)
    method: GET
    uri: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/00000/providers/Microsoft.MachineLearningServices/workspaces/00000/datastores?count=30&isDefault=true&orderByAsc=false
  response:
    body:
      string: '{"value": [{"id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/00000/providers/Microsoft.MachineLearningServices/workspaces/00000/datastores/workspaceblobstore",
        "name": "workspaceblobstore", "type": "Microsoft.MachineLearningServices/workspaces/datastores",
        "properties": {"description": null, "tags": null, "properties": null, "isDefault":
        true, "credentials": {"credentialsType": "AccountKey"}, "intellectualProperty":
        null, "subscriptionId": "00000000-0000-0000-0000-000000000000", "resourceGroup":
        "00000", "datastoreType": "AzureBlob", "accountName": "fake_account_name",
        "containerName": "fake-container-name", "endpoint": "core.windows.net", "protocol":
        "https", "serviceDataAccessAuthIdentity": "WorkspaceSystemAssignedIdentity"},
        "systemData": {"createdAt": "2023-04-08T02:53:06.5886442+00:00", "createdBy":
        "779301c0-18b2-4cdc-801b-a0a3368fee0a", "createdByType": "Application", "lastModifiedAt":
        "2023-04-08T02:53:07.521127+00:00", "lastModifiedBy": "779301c0-18b2-4cdc-801b-a0a3368fee0a",
        "lastModifiedByType": "Application"}}]}'
    headers:
      cache-control:
      - no-cache
      content-length:
      - '1372'
      content-type:
      - application/json; charset=utf-8
      expires:
      - '-1'
      pragma:
      - no-cache
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      vary:
      - Accept-Encoding
      x-cache:
      - CONFIG_NOCACHE
      x-content-type-options:
      - nosniff
      x-request-time:
      - '0.069'
    status:
      code: 200
      message: OK
- request:
    body: null
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - promptflow-azure-sdk/1.11.0.dev0 azure-ai-ml/1.15.0 azsdk-python-mgmt-machinelearningservices/0.1.0
        Python/3.11.5 (Windows-10-10.0.22621-SP0)
    method: GET
    uri: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/00000/providers/Microsoft.MachineLearningServices/workspaces/00000/datastores/workspaceblobstore
  response:
    body:
      string: '{"id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/00000/providers/Microsoft.MachineLearningServices/workspaces/00000/datastores/workspaceblobstore",
        "name": "workspaceblobstore", "type": "Microsoft.MachineLearningServices/workspaces/datastores",
        "properties": {"description": null, "tags": null, "properties": null, "isDefault":
        true, "credentials": {"credentialsType": "AccountKey"}, "intellectualProperty":
        null, "subscriptionId": "00000000-0000-0000-0000-000000000000", "resourceGroup":
        "00000", "datastoreType": "AzureBlob", "accountName": "fake_account_name",
        "containerName": "fake-container-name", "endpoint": "core.windows.net", "protocol":
        "https", "serviceDataAccessAuthIdentity": "WorkspaceSystemAssignedIdentity"},
        "systemData": {"createdAt": "2023-04-08T02:53:06.5886442+00:00", "createdBy":
        "779301c0-18b2-4cdc-801b-a0a3368fee0a", "createdByType": "Application", "lastModifiedAt":
        "2023-04-08T02:53:07.521127+00:00", "lastModifiedBy": "779301c0-18b2-4cdc-801b-a0a3368fee0a",
        "lastModifiedByType": "Application"}}'
    headers:
      cache-control:
      - no-cache
      content-length:
      - '1227'
      content-type:
      - application/json; charset=utf-8
      expires:
      - '-1'
      pragma:
      - no-cache
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      vary:
      - Accept-Encoding
      x-cache:
      - CONFIG_NOCACHE
      x-content-type-options:
      - nosniff
      x-request-time:
      - '0.097'
    status:
      code: 200
      message: OK
- request:
    body: null
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '0'
      User-Agent:
      - promptflow-azure-sdk/1.11.0.dev0 azure-ai-ml/1.15.0 azsdk-python-mgmt-machinelearningservices/0.1.0
        Python/3.11.5 (Windows-10-10.0.22621-SP0)
    method: POST
    uri: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/00000/providers/Microsoft.MachineLearningServices/workspaces/00000/datastores/workspaceblobstore/listSecrets
  response:
    body:
      string: '{"secretsType": "AccountKey", "key": "dGhpcyBpcyBmYWtlIGtleQ=="}'
    headers:
      cache-control:
      - no-cache
      content-length:
      - '134'
      content-type:
      - application/json; charset=utf-8
      expires:
      - '-1'
      pragma:
      - no-cache
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      x-cache:
      - CONFIG_NOCACHE
      x-content-type-options:
      - nosniff
      x-request-time:
      - '0.084'
    status:
      code: 200
      message: OK
- request:
    body: null
    headers:
      Accept:
      - application/xml
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - azsdk-python-storage-blob/12.19.0 Python/3.11.5 (Windows-10-10.0.22621-SP0)
      x-ms-date:
      - Thu, 09 May 2024 06:53:32 GMT
      x-ms-version:
      - '2023-11-03'
    method: HEAD
    uri: https://fake_account_name.blob.core.windows.net/fake-container-name/LocalUpload/000000000000000000000000000000000000/inputs.jsonl
  response:
    body:
      string: ''
    headers:
      accept-ranges:
      - bytes
      content-length:
      - '60'
      content-md5:
      - tiCwcZnEReXDaVrgfN3qAQ==
      content-type:
      - application/octet-stream
      last-modified:
      - Thu, 18 Apr 2024 06:39:03 GMT
      server:
      - Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
      vary:
      - Origin
      x-ms-blob-type:
      - BlockBlob
      x-ms-creation-time:
      - Thu, 18 Apr 2024 06:39:02 GMT
      x-ms-meta-name:
      - b71e395a-c049-4e64-8360-c72dd242006d
      x-ms-meta-upload_status:
      - completed
      x-ms-meta-version:
      - ce6436cb-e73a-4d3a-8a12-774ed1e58516
      x-ms-version:
      - '2023-11-03'
    status:
      code: 200
      message: OK
- request:
    body: null
    headers:
      Accept:
      - application/xml
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - azsdk-python-storage-blob/12.19.0 Python/3.11.5 (Windows-10-10.0.22621-SP0)
      x-ms-date:
      - Thu, 09 May 2024 06:53:36 GMT
      x-ms-version:
      - '2023-11-03'
    method: HEAD
    uri: https://fake_account_name.blob.core.windows.net/fake-container-name/az-ml-artifacts/000000000000000000000000000000000000/inputs.jsonl
  response:
    body:
      string: ''
    headers:
      server:
      - Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
      transfer-encoding:
      - chunked
      vary:
      - Origin
      x-ms-error-code:
      - BlobNotFound
      x-ms-version:
      - '2023-11-03'
    status:
      code: 404
      message: The specified blob does not exist.
- request:
    body: null
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - promptflow-azure-sdk/1.11.0.dev0 azure-ai-ml/1.15.0 azsdk-python-mgmt-machinelearningservices/0.1.0
        Python/3.11.5 (Windows-10-10.0.22621-SP0)
    method: GET
    uri: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/00000/providers/Microsoft.MachineLearningServices/workspaces/00000/datastores/workspaceblobstore
  response:
    body:
      string: '{"id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/00000/providers/Microsoft.MachineLearningServices/workspaces/00000/datastores/workspaceblobstore",
        "name": "workspaceblobstore", "type": "Microsoft.MachineLearningServices/workspaces/datastores",
        "properties": {"description": null, "tags": null, "properties": null, "isDefault":
        true, "credentials": {"credentialsType": "AccountKey"}, "intellectualProperty":
        null, "subscriptionId": "00000000-0000-0000-0000-000000000000", "resourceGroup":
        "00000", "datastoreType": "AzureBlob", "accountName": "fake_account_name",
        "containerName": "fake-container-name", "endpoint": "core.windows.net", "protocol":
        "https", "serviceDataAccessAuthIdentity": "WorkspaceSystemAssignedIdentity"},
        "systemData": {"createdAt": "2023-04-08T02:53:06.5886442+00:00", "createdBy":
        "779301c0-18b2-4cdc-801b-a0a3368fee0a", "createdByType": "Application", "lastModifiedAt":
        "2023-04-08T02:53:07.521127+00:00", "lastModifiedBy": "779301c0-18b2-4cdc-801b-a0a3368fee0a",
        "lastModifiedByType": "Application"}}'
    headers:
      cache-control:
      - no-cache
      content-length:
      - '1227'
      content-type:
      - application/json; charset=utf-8
      expires:
      - '-1'
      pragma:
      - no-cache
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      vary:
      - Accept-Encoding
      x-cache:
      - CONFIG_NOCACHE
      x-content-type-options:
      - nosniff
      x-request-time:
      - '0.122'
    status:
      code: 200
      message: OK
- request:
    body: null
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '0'
      User-Agent:
      - promptflow-azure-sdk/1.11.0.dev0 azure-ai-ml/1.15.0 azsdk-python-mgmt-machinelearningservices/0.1.0
        Python/3.11.5 (Windows-10-10.0.22621-SP0)
    method: POST
    uri: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/00000/providers/Microsoft.MachineLearningServices/workspaces/00000/datastores/workspaceblobstore/listSecrets
  response:
    body:
      string: '{"secretsType": "AccountKey", "key": "dGhpcyBpcyBmYWtlIGtleQ=="}'
    headers:
      cache-control:
      - no-cache
      content-length:
      - '134'
      content-type:
      - application/json; charset=utf-8
      expires:
      - '-1'
      pragma:
      - no-cache
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      x-cache:
      - CONFIG_NOCACHE
      x-content-type-options:
      - nosniff
      x-request-time:
      - '0.085'
    status:
      code: 200
      message: OK
- request:
    body: null
    headers:
      Accept:
      - application/xml
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - azsdk-python-storage-blob/12.19.0 Python/3.11.5 (Windows-10-10.0.22621-SP0)
      x-ms-date:
      - Thu, 09 May 2024 06:53:46 GMT
      x-ms-version:
      - '2023-11-03'
    method: HEAD
    uri: https://fake_account_name.blob.core.windows.net/fake-container-name/LocalUpload/000000000000000000000000000000000000/inputs.jsonl
  response:
    body:
      string: ''
    headers:
      accept-ranges:
      - bytes
      content-length:
      - '60'
      content-md5:
      - tiCwcZnEReXDaVrgfN3qAQ==
      content-type:
      - application/octet-stream
      last-modified:
      - Thu, 18 Apr 2024 06:39:03 GMT
      server:
      - Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
      vary:
      - Origin
      x-ms-blob-type:
      - BlockBlob
      x-ms-creation-time:
      - Thu, 18 Apr 2024 06:39:02 GMT
      x-ms-meta-name:
      - b71e395a-c049-4e64-8360-c72dd242006d
      x-ms-meta-upload_status:
      - completed
      x-ms-meta-version:
      - ce6436cb-e73a-4d3a-8a12-774ed1e58516
      x-ms-version:
      - '2023-11-03'
    status:
      code: 200
      message: OK
- request:
    body: null
    headers:
      Accept:
      - application/xml
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - azsdk-python-storage-blob/12.19.0 Python/3.11.5 (Windows-10-10.0.22621-SP0)
      x-ms-date:
      - Thu, 09 May 2024 06:53:49 GMT
      x-ms-version:
      - '2023-11-03'
    method: HEAD
    uri: https://fake_account_name.blob.core.windows.net/fake-container-name/az-ml-artifacts/000000000000000000000000000000000000/inputs.jsonl
  response:
    body:
      string: ''
    headers:
      server:
      - Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
      transfer-encoding:
      - chunked
      vary:
      - Origin
      x-ms-error-code:
      - BlobNotFound
      x-ms-version:
      - '2023-11-03'
    status:
      code: 404
      message: The specified blob does not exist.
version: 1
