name: step_create_python_environment
inputs:
  pipFilePath:
    required: false
    default: "src/promptflow/dev_requirements.txt"
    type: string
  pythonVersion:
    required: false
    default: "3.9"
    type: string
runs:
  using: composite
  steps:
  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.pythonVersion }}
  - uses: snok/install-poetry@v1
  - run: |
      python -m pip install --upgrade pip
      pip install -r ${{ inputs.pipFilePath }}
      pip freeze
    shell: pwsh
