parameters:
- name: promptflowCsPat
  displayName: "PAT to clone csharp repository"
  type: string
- name: flowProjectRelativePath
  displayName: "Flow Project Relative Path"
  type: string

steps:
  - task: UseDotNet@2
    inputs:
      version: '6.x'
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9.x'
      architecture: 'x64'

  - task: PowerShell@2
    displayName: 'Install promptflow cli'
    inputs:
      targetType: 'inline'
      script: |
        Set-PSDebug -Trace 1
        pip install -r src/promptflow/dev_requirements.txt
        pip install src/promptflow-tracing
        pip install src/promptflow-core[executor-service]
        pip install src/promptflow-devkit
        pip install src/promptflow-azure
        pip install src/promptflow-recording
        pip freeze

  - task: PowerShell@2
    displayName: 'Clone csharp repository'
    inputs:
      targetType: 'inline'
      script: |
        git clone https://$(PROMPTFLOW_CS_PAT)@dev.azure.com/msdata/Vienna/_git/PromptflowCS csharp

  - task: NuGetAuthenticate@1

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '$(flowProjectRelativePath)/**/*.csproj'
      feedsToUse: 'config'
      nugetConfigPath: '$(flowProjectRelativePath)/nuget.config'
    displayName: 'dotnet restore'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '$(flowProjectRelativePath)/**/*.csproj'
      feedsToUse: 'config'
      nugetConfigPath: '$(flowProjectRelativePath)/nuget.config'
    displayName: 'dotnet build'
