name: test_data_gen_conda_env
channels:
  - defaults
dependencies:
  - python=3.10.12
  - pip=23.2.1
  - pip:
    - mldesigner==0.1.0b18
    - llama_index==0.9.48
    - docx2txt==0.8
    - promptflow>=1.7.0
