name: check_enforcer

on:
  pull_request:
    branches: [ main ]

jobs:
  check_enforcer:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: env | sort >> $GITHUB_OUTPUT
      - name: Python Setup - ubuntu-latest - Python Version 3.9
        uses: "./.github/actions/step_create_python_environment"
        with:
          pythonVersion: 3.9
      - run: pip install -r ${{ github.workspace }}/examples/dev_requirements.txt
      - name: Summarize check status
        id: summarize_check_status
        working-directory: ${{ github.workspace }}
        shell: pwsh
        run: |
            python ${{ github.workspace }}/scripts/check_enforcer/check_enforcer.py -t "${{ github.workspace }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SNIPPET_DEBUG: 1
